[config]
schemaVersion = "0.0.1"

[package]
namespace = "Windows10CE"
name = "Old_Fecundity"
versionNumber = "1.0.0"
description = "Reverts the fecundity nerf in Kaycee's Mod"
websiteUrl = "https://github.com/Windows10CE/OldFecundity"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Inscryption = "5.4.1701"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/netstandard2.0/OldFecundity.dll"
target = "OldFecundity.dll"

[publish]
repository = "https://inscryption.thunderstore.io"
communities = [ "inscryption" ]
categories = [ "act-i", "tweaks" ]